name: istudy_courses
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.0
  cupertino_icons: ^1.0.8
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.2.0
  cloud_firestore: ^6.0.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  firebase_storage: ^13.0.0
  http: ^1.4.0
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.6.1
  img_picker: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
